DEBUG 2023-08-18 08:09:34.469 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-08-18 08:09:34.469 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-08-18 08:09:34.470 UTC: 	 Executing command: 'resubmit'
DEBUG 2023-08-18 08:09:34.470 UTC: 	 Found CRAB cache file /lustrehome/mbuonsante/.crab3
ERROR 2023-08-18 08:09:34.472 UTC: 	 Error: crab_DsPhiPi_reco2023_RunB_stream0_cfg.py is not a valid CRAB project directory.
ERROR 2023-08-18 08:09:34.472 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_DsPhiPi_reco2023_RunB_stream0_cfg.py is not a valid CRAB project directory.
INFO 2023-08-18 08:09:34.481 UTC: 	 Log file is /lustrehome/mbuonsante/Tau_3mu/CMSSW_13_0_10/src/CrabSubmission/Data_2023/SkimPhiPi/reco2023_RunB/crab.log
DEBUG 2023-08-18 08:09:53.636 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-08-18 08:09:53.636 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-08-18 08:09:53.636 UTC: 	 Executing command: 'resubmit'
DEBUG 2023-08-18 08:09:53.636 UTC: 	 Found CRAB cache file /lustrehome/mbuonsante/.crab3
ERROR 2023-08-18 08:09:53.638 UTC: 	 Cannot find .requestcache file in CRAB project directory /lustrehome/mbuonsante/Tau_3mu/CMSSW_13_0_10/src/CrabSubmission/Data_2023/SkimPhiPi/reco2023_RunB/crab_projects
ERROR 2023-08-18 08:09:53.638 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 502, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/ClientUtilities.py", line 440, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /lustrehome/mbuonsante/Tau_3mu/CMSSW_13_0_10/src/CrabSubmission/Data_2023/SkimPhiPi/reco2023_RunB/crab_projects
INFO 2023-08-18 08:09:53.642 UTC: 	 Log file is /lustrehome/mbuonsante/Tau_3mu/CMSSW_13_0_10/src/CrabSubmission/Data_2023/SkimPhiPi/reco2023_RunB/crab.log
DEBUG 2023-08-18 08:14:01.946 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-08-18 08:14:01.946 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-08-18 08:14:01.946 UTC: 	 Executing command: 'resubmit'
DEBUG 2023-08-18 08:14:01.947 UTC: 	 Found CRAB cache file /lustrehome/mbuonsante/.crab3
ERROR 2023-08-18 08:14:01.948 UTC: 	 Error: crab_projects/crab_SkimDsPhiPi_2023eraB_stream4_Mini_v3/crab.log is not a valid CRAB project directory.
ERROR 2023-08-18 08:14:01.948 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_SkimDsPhiPi_2023eraB_stream4_Mini_v3/crab.log is not a valid CRAB project directory.
INFO 2023-08-18 08:14:01.951 UTC: 	 Log file is /lustrehome/mbuonsante/Tau_3mu/CMSSW_13_0_10/src/CrabSubmission/Data_2023/SkimPhiPi/reco2023_RunB/crab.log
DEBUG 2023-08-18 08:16:13.159 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-08-18 08:16:13.160 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-08-18 08:16:13.160 UTC: 	 Executing command: 'resubmit'
DEBUG 2023-08-18 08:16:13.160 UTC: 	 Found CRAB cache file /lustrehome/mbuonsante/.crab3
ERROR 2023-08-18 08:16:13.161 UTC: 	 Error: 230817_130907 is not a valid CRAB project directory.
ERROR 2023-08-18 08:16:13.162 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: 230817_130907 is not a valid CRAB project directory.
INFO 2023-08-18 08:16:13.166 UTC: 	 Log file is /lustrehome/mbuonsante/Tau_3mu/CMSSW_13_0_10/src/CrabSubmission/Data_2023/SkimPhiPi/reco2023_RunB/crab.log
